name: Reusable Build

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装 uv
        run: pip install uv

      - name: 安装依赖
        run: uv sync

      - name: 打包 exe
        run: uv run pyinstaller --name night-watcher --noconsole --hidden-import requests --icon resources/icon.ico --add-data "adapter;adapter" --add-data "themes;themes" --add-data "resources;resources" --add-data "i18n;i18n" main.py

      - name: 上传 artifact
        uses: actions/upload-artifact@v4
        with:
          name: night-watcher
          path: dist/night-watcher/
